### ISSUE TITLE
Plans

### ISSUE THREAD

**Issue by xilec** [paupino/rust-decimal#136]
Have you any plans for stabilization or moving forward in short term for this crate?

**Comment by paupino** [comment]
I'm currently using this for some of my own financial projects and am keen to see this reach version 1. 

I have no formal plans for stabalization at present however I would like to have some more confidence that reasonable overflow and underflow scenarios have been covered. One user suggested QuickCheck (via #129) as something which may cover some of these edge scenarios however I'm not quite sure how that would integrate at this point in time.

I'm certainly open for any assistance or gap identification in order to get it to v1 and certainly appreciate your assistance and support thus far - thank you!
