### ISSUE TITLE
What's the performance story for this project?

### ISSUE THREAD

**Issue by jonathanstrong** [paupino/rust-decimal#148]
Hey,

I am currently a decNumber/decimal user and was interested in this library because hacking on the decNumber C codebase is pretty gnarly. However I ran your comparison benchmarks and saw there is still a long way to go. (That's no slight, this is a new project and expected).

For some background context, I am using `d128` for correct precision/rounding in financial applications, but always find myself grappling with the dramatic performance hit I get from a decimal type versus a `f64` or other primitive type. Just today, I switched a `d128` cumulative sum calculation to `f64` and saw a 90% speedup. Honestly there are times when I wonder if decimal types are worth it. Maybe I could just take some steps to mitigate potential floating point issues.

From that perspective, I was interested in your thoughts on what's possible for a decimal type in terms of performance, how you're coming at the issue, and how you deal with similar issues you face. What are the challenges? And do you see potential shortcuts that could produce performant solutions for constrained use-cases?  What I have in mind is, for instance, `d128` can handle up to 34 significant digits, but I don't ever need 34 significant digits. Perhaps limiting precision could be faster and still correct.

I'm definitely interested to see where this project goes, if you have any thoughts along these lines I'd be very anxious to hear them. Thanks!

**Comment by paupino** [comment]
Thank you; these are some great questions! 

The primary priorities for this project are (in order):

1. Correctness - avoid underflow/overflow/bitwise issues, or rather be pedantic about when they may be encountered and handle appropriately.
2. Performance - using this library should provide a set level of accuracy without a significant performance overhead.

Ultimately, floating point errors are very real which is why this project came to be. Even with appropriate rounding, there are [theoretical scenarios](https://docs.oracle.com/cd/E19957-01/806-3568/ncg_goldberg.html) which can cause unexpected results. There are workarounds which can, for example, involve conversion to and from integers however they typically come at the expense of performance and losing a level of precision. 

As mentioned: performance has been a goal of this project and as it has evolved over time there have been dramatic increases - particularly in trivial calculations which involve addition, subtraction and multiplication. Calculations involving division, as you've no doubt seen, are significantly slower and are yet to be addressed. Unfortunately division is a fundamental operation which means it is definitely important to optimize. Consequently, I've been experimenting on and off (when I have time) about how I can improve division performance without introducing "correctness" errors. That has recently lead me on a slight tangent with fuzz testing the decimal library to ensure that performance improvements don't introduce leaky implementations.

That being said: I think there are some both easy and wins that have come with recent rust stabilizations. For example, with `u128` being stabilized: early experimentation shows it has some great benefits by letting the compiler deal with word positioning. Likewise the use of `const fn` has shown some positive improvements for certain operations etc.

In saying that, I would like to further dive into the _fundamental_ performance story. That is, improving performance without needing to dive into unsafe code, simply from an operational perspective. In order to do that effectively, I first need to address the confidence level problem which covers "edge case" correctness. Currently, that is my main worry so once that has been addressed then I'd be willing to really deep dive into further performance level improvements.

Hopefully that all makes sense and answers your questions. I really do thank you for your interest in the project - it's these kind of conversations which really give me hope and "the drive" to keep building this library. I'm absolutely open to criticism about my prioritization ordering and of course if you have any help/suggestions you can provide they are most certainly appreciated!

**Comment by paupino** [comment]
Closing this for now. Division was the largest troublesome operation which was addressed in #303. We'll likely move over other operations towards this in v1.12 via #335 .
