### ISSUE TITLE
Add Continuous Integration

### ISSUE THREAD

**Issue by JP-Ellis** [paupino/rust-decimal#15]
Continuous integration should be added to test the crate on Rust stable, beta and nightly.

Along with this, it will possible to have the `master` branch be protected so that only changes which pass the CI can be merged, and then the main development will happen on the `develop` branch (where things might break temporarily).

**Comment by paupino** [comment]
We could also add a PR webhook here so that only PR's that pass the build check can be merged. I'm more inclined to do that and continue using tags for releases than using `develop` however am open for discussion here. By the way, the master branch is currently protected against force merges etc so a PR is (now) required in order to get something into master (hence why the PR webhook could work).

**Comment by JP-Ellis** [comment]
I would definitely set up Github to refuse pull requests until they pass the CI tests; then it's up to you whether you want to use a `develop` branch.  It's always possible to create new branches as need be.

**Comment by paupino** [comment]
I've now set it up so that PR's into `master` require TravisCI builds to pass. Now that TravisCI builds _do_ pass I think we can close this issue.

**Comment by paupino** [comment]
Also, have added to the Readme page.

**Comment by paupino** [comment]
I'm new to using Travis so I may have set this up incorrectly for forks. Is it expected that you'd need to authorize your fork on Travis also @JP-Ellis ?

**Comment by paupino** [comment]
Nope, nevermind. Travis just requires conflicts to be resolved first. All good.
