### ISSUE TITLE
[Question] Workaround issue #151

### ISSUE THREAD

**Issue by gbonnema** [paupino/rust-decimal#158]
I am new to Rust and learning as I go. I have the problem described in issue #151 and want to apply the workaround (a macro for dec). However, where do I place the macro definition so I can access it from the other modules in my project?

my main module definition (src/lib.rs) looks something like this:
```
extern crate rust_decimal;
  2 //extern crate rust_decimal_macros;
  3 
 11 pub mod budget;
 12 pub mod bin {
 13     pub mod controller;
 14     pub mod ui;
 15 }

```
I put the macro definition in here, but that does not appear to work. So if I want the macro generally accessible, how do I do that?
The macro I am referring to is:
```
  4 macro_rules! dec {
  5     ($e:expr) => {{
  6         use std::str::FromStr;
  7         Decimal::from_str(stringify!($e)).unwrap()
  8     }};
  9 }
```

P.S. I also wonder why the issue is closed, as rust stable still produces this problem

**Comment by paupino** [comment]
Thanks for the question! Hope you're enjoying learning Rust - it's a fantastic language to write once you get over the initial idiosyncrasies. 

This, unfortunately, appears to be a documentation issue. In order to use the Rust macro you simply need to "use" the macro definition.

i.e.

```rust
// You can leave the extern's out in Rust 2018
extern crate rust_decimal;
extern crate rust_decimal_macros;

// This is the key difference: I need to update the docs to explicitly import the macro
use rust_decimal_macros::dec; 

fn main() {
    println!("This is a decimal number: {}", dec!(100.56));
}
```

This runs successfully on Rust Stable only recently due to a [recent PR](https://github.com/paupino/rust-decimal/pull/154).

If this _doesn't_ work for you still can you please let me know your rustc and cargo versions?

Thanks!

**Comment by gbonnema** [comment]
Atm it doesn't work. I did a rustup update, but it didn't change anything (see screenshot which contains source and messages in one screen). Maybe I need something other than `rustup update`?
![2019-02-16-error-msg-decimal](https://user-images.githubusercontent.com/2283947/52904120-ae3f2d00-3227-11e9-96d3-b5ad98a08706.png)

**Comment by gbonnema** [comment]
Cargo version is : 
```
cargo --version
cargo 1.32.0 (8610973aa 2019-01-02)

```

**Comment by paupino** [comment]
Can you specify what your `Cargo.toml` dependencies are - specifically for `rust_decimal` and `rust_decimal_macros`? Are you using `0.11.1`?

If you are then there is a possibility this is a distro issue which I'll need to do some further investigation on.

**Comment by paupino** [comment]
Sorry - I should have mentioned the `Cargo.lock` entries. These will specify your current version in use.

**Comment by gbonnema** [comment]
Included both Cargo.toml and Cargo.lock
[cargo.zip](https://github.com/paupino/rust-decimal/files/2872812/cargo.zip)

**Comment by gbonnema** [comment]
Apparantly I use version="0.10.2" of both rust_decimal and rust_decimal_macros. I will compile with 0.11.1 if I can. Give me a sec to try that out.

**Comment by paupino** [comment]
Cool! Glad it's working now.

> I wonder, whether there is a way to always have the last stable of a crate: is there?

It really depends on the crate. I am probably looking at formally releasing version "1.0" soon since the rate of change has slowed dramatically which means you _would_ be able to simply put `rust_decimal = "1"` in the `Cargo.toml`. Since it's still pre-1.0 you could potentially use "*" for the meantime (or I think "0" works too) however it's really on me to increment the major version - I just haven't got around to it. This gives me some revived motivation so I'll see if I can put together a roadmap towards 1.0 and beyond over the next couple of weeks.

For the meantime, since your problem is solved I'll close this issue but please let me know if you have any further questions!
