### ISSUE TITLE
panic with 'attempt to negate with overflow' in from_i32/from_i64

### ISSUE THREAD

**Issue by 0e4ef622** [paupino/rust-decimal#171]
Calling `Decimal::from_i32(i32::min_value())` or `Decimal::from_i64(i64::min_value())` panics in debug mode.

**Comment by paupino** [comment]
This is due to an assumption that is made in code (at present) whereby I remove the sign to put into the decimal. Unfortunately, `abs(-2147483648) > 2147483647`. 

The attached PR fixes this by leveraging larger types. Accordingly, I want to keep leveraging the 128bit types going forward as it it can simplify things greatly.

**Comment by 0e4ef622** [comment]
Just FYI this could've been fixed by just using `wrapping_neg`. The result was actually correct in release mode.
