### ISSUE TITLE
`UnpackedDecimal` is marked `pub`, but not exported

### ISSUE THREAD

**Issue by 0e4ef622** [paupino/rust-decimal#173]
Is this intentional?

**Comment by paupino** [comment]
It isn't however I'm intended to keep it this way. The reason for this is because the `UnpackedDecimal` is more of an internal implementation detail that is really only useful for rust-decimal debuggers. I do think however that this exposes a problem with unclear documentation. We could potentially define that a bit further rather than just saying it returns the undocumented `UnpackedDecimal`.
