### ISSUE TITLE
Why are Decimals serialized as strings in JSON?

### ISSUE THREAD

**Issue by ufoscout** [paupino/rust-decimal#205]
Shouldn't Decimal(s) be serialized as numbers in JSON format?

I am a little surprised by this test in source code:
```rust
    #[test]
    fn serialize_decimal() {
        let record = Record {
            amount: Decimal::new(1234, 3),
        };
        let serialized = serde_json::to_string(&record).unwrap();
        assert_eq!("{\"amount\":\"1.234\"}", serialized);
    }
```
Due to the fact that arbitrary precision is fully supported by serde, I expected the serialization to produce: `{"amount": 1.234}` or at least to have an option to choose the output format.

**Comment by paupino** [comment]
The main thought process behind this was because most consuming parsers will treat this number as a float and potentially lose precision. That being said, it's certainly possible to make this an option for serialization. 
What's the use case that you're looking at?

**Comment by ufoscout** [comment]
Hi @paupino 
I wrote a new component of a distributed system using this library. 
The existing pieces of the system send and receive data in JSON format. One of the problems is that some components are written in scripting languages (e.g javascript) and they do not expect to receive numbers as strings, so, when this happens, every calculation performed becomes wrong (e.g `x+y` is executed as a string concatenation instead of numeric addition).
The lack of precision on the JS systems is not a problem for the system.
This problem never happened before because most of the components are written in Java and the BigDecimals are by default serialized as numbers (i.e. without quotes) in JSON.

**Comment by jbg** [comment]
If supported, this definitely needs to be an option. Many (most?) people using this library will be using it for financial things, where it's not acceptable to serialise arb-precision decimals to numbers in JSON if they're going to be consumed by JS, since JS will treat it as a float.

@ufoscout out of curiosity, may I ask why you're using rust-decimal rather than floats if precision is not an issue? a suitable workaround for now would be to write your own serialiser impl that converts the Decimal to a float and then delegates to the normal float serialiser.

**Comment by ufoscout** [comment]
@jbg the precision is not an issue only in the services based on nodejs because they simply aggregate data and show some high-level dashboards.
Absolute precision is required in most of the other components of the system.

**Comment by paupino** [comment]
Added an option for this in #207
