### ISSUE TITLE
Strange conversion to PgNumeric

### ISSUE THREAD

**Issue by Rexagon** [paupino/rust-decimal#241]
Recently I came across strange behavior.

This code:
```
let value = Decimal::from_str("0.000001660").unwrap();
println!("{:?}", value);
let pg = PgNumeric::from(value);
println!("{:?}", pg);

let dec = Decimal::try_from(pg).unwrap();
println!("{:?}", dec);
```

prints:
```
0.000001660
Positive { weight: -3, scale: 9, digits: [166, 0] }
0.000000166
```

Trailing zero causes this problem. Value `0.00000166` is serialized how it should be

**Comment by serejkaaa512** [comment]
Seems like there is a need of normalisation before serialising decimal to Postgres value.
If I add  `.normalize()` before `to_postgres()` this issue get fixed.

**Comment by paupino** [comment]
This does look like incorrect behavior. I believe the issue is due to the weight being `-3` instead of `-4` so probably stems from here: https://github.com/paupino/rust-decimal/blob/master/src/postgres.rs#L237

While normalization works around this issue, it still means that 1 significant figure of precision is lost. I'll take a look at this later today and see what I can find.

**Comment by serejkaaa512** [comment]
Took a look again. Normalization doesn't work correctly also. For example `0.00000166650000` doesn't serialise and deserialise correctly. Comparing implementation with bigdecimal and tests in it, looks like both serialisation and deserialisation in some cases gives wrong values in postgresql.

**Comment by paupino** [comment]
From investigation, this looks specific to the write logic as opposed to the read logic. This is definitely isolated to the `to_postgres` function and exists in both the Diesel logic as well as the standard PG logic. It's not trailing zeros per se, but rather trailing zeros when they extend the PG group logic (i.e. when the last group is zero). 

It seems like this is to do with the algorithm doing an "exhaustive" loop until the mantissa is zero. Because it exits "early" it effectively truncates instead of adding in the trailing zero's. 

I want to ensure any solution does some exhaustive testing around this scenario (e.g. including multiple trailing zero groups) so will work on the solution over the next couple of days to ensure I cover all edge cases.

**Comment by serejkaaa512** [comment]
I have made my implementation of serialise, deserialize based on PG docs and bigdecimal impls. Added some tests of trailing zeroes. If you want I can do a pr?

**Comment by serejkaaa512** [comment]
Added PR #243
