### ISSUE TITLE
Changing the order of calculations changes result

### ISSUE THREAD

**Issue by rokit** [paupino/rust-decimal#268]
I think I found a bug. This test passes:
```
        let num = dec!(3) * dec!(1) / dec!(3);
        assert_eq!(num, dec!(1));
```
But this one doesn't:
```
        let num = dec!(1) / dec!(3) * dec!(3);
        assert_eq!(num, dec!(1));

output:
  left: `0.9999999999999999999999999999`,
 right: `1`
```
using:
rust_decimal = "1.7.0"
rust_decimal_macros = "1.7.0"

**Comment by paupino** [comment]
The second result is explicitly due to the order of operations (i.e. BEDMAS). Because division is prioritized before multiplication at the trait level, the second example is calculating `1 / 3` (i.e. `1.div(3)`) before then multiplying by `3`.
Rust Decimal is unable to represent rational numbers - consequently, it evaluates the division of `1 / 3` first which of course gives `0.33` recurring. This loses precision because we can only represent a certain number of decimal points within 96 bits - this value being: `0.3333333333333333333333333333`. Multiplying this number by three gives us the expected output of `0.9999999999999999999999999999`.

There are some crates that can help represent numbers this way. One such example is: https://github.com/rust-num/num-rational

Consequently, closing this as it is working as "expected" - at least in regards to how this crate is implemented in terms of the decimal layout.

**Comment by rokit** [comment]
Thanks for the detailed explanation!
