### ISSUE TITLE
`to_128()` uses `u64`

### ISSUE THREAD

**Issue by fredfortier** [paupino/rust-decimal#282]
Calling `to_128()` returns `None` when the number overflows 64 bits. 

If I go to definition, I get into the num-trait crate with the `u64` default implementation:
```rust
    #[cfg(has_i128)]
    fn to_u128(&self) -> Option<u128> {
        self.to_u64().map(From::from)
    }
```
How can I give my program a real `u128` implementation? I tried adding this feature: `#![feature(i128)]` and including the `num-integer` dependency in my crate, but it does not work. I apologize if the solution is obvious, I just don't know how to do it.

**Comment by paupino** [comment]
Since we already have an implicit dependency for `i128` it wouldn't be too much of a lift to implement this for Rust Decimal. At the moment, the trait definition would need to be overriden for this to behave correctly however one workaround until we implement the trait would be to convert into raw parts. 

i.e. similar to this: https://github.com/paupino/rust-decimal/blob/af0d700a4aab8d2d8083a3fcf1604d8dbe7a7de9/src/decimal.rs#L2633-L2645
You can get the unpacked decimal (raw parts) using `.unpack()`.

e.g.
```
    fn to_u128(value: &Decimal) -> Option<u128> {
        if value.is_sign_negative() {
            return None;
        }

        let d = value.trunc().unpack();
        Some((u128::from(d.hi) << 64) | (u128::from(d.mid) << 32) | u128::from(d.lo))
    }
```

I'll see if I can get a more formalized way of doing this into the next version, however for now the above function should provide a workaround.
