### ISSUE TITLE
panic while calc sqrt for a positive number

### ISSUE THREAD

**Issue by wugifer** [paupino/rust-decimal#347]
the code below panic:

    fn main() {
        let a = dec!(0.0000000000000000000000000001);
        let c = a / dec!(2);
        println!("{:?}", c);
        let _b = a.sqrt();
    }

the output is:

0
thread 'main' panicked at 'Division by zero', D:\...\rust_decimal-1.11.1\src\decimal.rs:4227:37

I found this in source code, maybe with error:

    # maths.rs, line 127
    fn sqrt(&self) -> Option<Decimal> {
        if self.is_sign_negative() {
            return None;
        }

        if self.is_zero() {
            return Some(Decimal::zero());
        }

        let mut result = self / TWO;                       // <-- here, in my case, result == 0
        let mut last = result + Decimal::one();

        let mut circuit_breaker = 0;
        while last != result {
            circuit_breaker += 1;
            assert!(circuit_breaker < 1000, "geo mean circuit breaker");

            last = result;
            result = (result + self / result) / TWO;           // <-- and here, with risk
        }

        Some(result)
    }

Thanks

**Comment by paupino** [comment]
Hi @wugifer, thanks for the submission! 

As I look at this, I can see a number of improvements that can be made. This currently constrains itself to a scale of 28 and consequently trips over itself with the divide by 2. If you look at how division is implemented internally, however, I actually bump the precision up before rounding it back into 28 decimal points. I think, since the result is within the bounds of Decimal representation (i.e. `1 * 10^-14`) that this logic could also benefit from leveraging the internal division logic before rounding. Fortunately, I'm currently in the middle of refactoring a lot of the operation logic which will actually make this approach a whole lot easier. 

Anyway, there are few things that _could_ be done:
1. We early exit on `0` - I'm not a fan of this as it would mean an incorrect result.
2. We return `None` when result == `0` - this is possible, however may hide future problems too (how many times would `result` be `0` in reality?).
3. Modify `sqrt` to use internal representation division / addition to maintain precision.

While 1 and 2 are quick fixes I'm much more inclined to go with option 3 since it means a fundamentally correct approach to `sqrt`. 1 would give incorrect results, and 2 feels like it's sweeping dirt under a rug.

I'm happy to take a look at this issue, however I want to finish up #335 first since it may change the fundamental approach.
