### ISSUE TITLE
Why bits 0-15 is unused?

### ISSUE THREAD

**Issue by Silentdoer** [paupino/rust-decimal#409]
why no use it to expand decimal's precision ?

**Comment by paupino** [comment]
The primary reason this was designed this way was to closely match the behavior of the dotnet Decimal number library. When this library was first being designed in 2015 I was originally wanting to serialize/deserialize across the wire between .NET and Rust. Since then, that project is no more however the original design constraint has kind of... stuck...  Of course, the C impl of the 128 bit decimal (`decNumber`) DOES use these additional bits - which is what [decimal](https://docs.rs/decimal/2.1.0/decimal/) wraps.

Additional precision is definitely something that I was planning to look at in version 2 of the library. Using the additional bits requires a substantial amount of work to handle the partial overflow across pretty much every operation - hence is really a V2 size task. Also, if I'm going that route then variable precision using const generics would also be an appealing route to investigate.
