### ISSUE TITLE
Request: Generate error when more more fractional digits than possible to store?

### ISSUE THREAD

**Issue by ivanschuetz** [paupino/rust-decimal#411]
Is it possible to make the string parsing error if it contains more fractional digits than what appears to be possible to store (28)?

**Comment by paupino** [comment]
This is interesting, and something that I can see as being useful when absolute precision is required. It's certainly possible to create a function that would return an error instead of rounding. 

One way to approach this in the meantime would be to do something like:

```rust
let number = "12345";
let parsed = Decimal::from_str(number).unwrap();
if parsed.to_string().ne(number) {
  // Some error
}
```
The trade off, of course, is that it isn't very efficient due to the additional conversion back to a string.

Anyway, certainly a feature that we can look into! It certainly wouldn't be too hard to implement.

**Comment by schungx** [comment]
Or maybe modify `from_str` to error out when there are too many digits?

**Comment by paupino** [comment]
Unfortunately that'd change the existing behavior of the interface. It currently behaves similarly to other libraries (e.g. [Decimal.Parse](https://docs.microsoft.com/en-us/dotnet/api/system.decimal.parse?view=net-5.0)) in that it'll round instead of underflow. I know I've got apps depending on this behavior so I can only imagine others would also be reliant on this existing behavior.

To be clear, it already errors on overflow - however currently rounds instead of underflowing. A separate function could be generated to change that behavior.

**Comment by ivanschuetz** [comment]
Thank you!
