### ISSUE TITLE
Why limit MAX_I128_REPR less than rust i128::MAX?

### ISSUE THREAD

**Issue by wangfenjin** [paupino/rust-decimal#427]
https://github.com/paupino/rust-decimal/blob/43c3a2caf53971aaab1b9e3c4eb4425485f59cb2/src/constants.rs#L28

https://doc.rust-lang.org/std/primitive.i128.html#associatedconstant.MAX

**Comment by paupino** [comment]
Hi @wangfenjin - the reason for this is because by design, the maximum mantissa representation is currently capped at 96 bits with the remaining 32 bits reserved for the scale (`e`) as well as the sign. The `MAX_I128_REPR` in this case is the maximum set of bits that fit into 96 bits / 12 bytes. 

[Future versions](https://github.com/paupino/rust-decimal/issues/354) of Rust Decimal may leverage const generics allowing for configurable size / precision however in the meantime there are no plans to extend the 96 bit mantissa for version `1.x`.
