### ISSUE TITLE
Significant figure rounding calculates SF incorrectly for numbers 0 < x < 1

### ISSUE THREAD

**Issue by hniksic** [paupino/rust-decimal#437]
This is a followup to #430. Using the same test function:

```rust
fn round3up(d: Decimal) -> Decimal {
    d.round_sf_with_strategy(3, RoundingStrategy::AwayFromZero).unwrap()
}
```

The assertion `assert_eq!("0.0124", round3up("0.012301".parse().unwrap()).to_string())` fails, and I'd expect it to pass.

I'd expect it to pass because, even though the digit following `0.0123` is 0, the number is still larger than `0.0123`, so it must be rounded up to `0.0124` (at least when rounding to three significant digits and with the `AwayFromZero` rounding strategy).

This is how e.g. Python's `decimal` behaves:

```
>>> import decimal
>>> d = decimal.Decimal(0.012301)
>>> d
Decimal('0.012300999999999999434674435860870289616286754608154296875')
>>> c = decimal.getcontext()
>>> c.prec = 3
>>> c.rounding = decimal.ROUND_UP
>>> c.create_decimal(d)
Decimal('0.0124')  # note 0.0124, even though the number is 0.012300999...

# test with other precisions
>>> c.prec = 2
>>> c.create_decimal(d)
Decimal('0.013')
>>> c.prec = 1
>>> c.create_decimal(d)
Decimal('0.02')
```

**Comment by paupino** [comment]
Thanks for this. I had made an assumption when writing this that isn't actually correct. I had assumed that `0`s to the right of the decimal are significant. This is true, but only the integral portion is greater than `0`. When it isn't (as in this case), those `0`s aren't significant since we can simplify the number down to something like `1.24 x 10^-2` (i.e. `1.24` is significant).

It shouldn't be too hard to fix. I'll take a look at it hopefully sometime this week.

**Comment by hniksic** [comment]
Thanks for looking into it. Please feel free to double-check, as I am not a mathematician, nor any kind of expert in the field. That's why I checked with Python to make sure I'm not making a mistake. Python's `decimal` module is extremely well tested to conform to the relevant standards, so `rust_decimal` could probably do worse than following its behavior.
