### ISSUE TITLE
Is the serialization of decimal memcomparable?

### ISSUE THREAD

**Issue by lmatz** [paupino/rust-decimal#463]
Hello and thank you for this crate!

Our project intends to rely on the `memcmp` of the serialization of decimals, thus I am curious:
1. Can `Decimal::from_f32(XXX).serialize()` be memcompared with `Decimal::from_f32(YYY).serialize()`?
2. Can `Decimal::from_f32(XXX).serialize()` be memcompared with `Decimal::from_f64(YYY).serialize()`?
3. Can `Decimal::from_f64(XXX).serialize()` be memcompared with `Decimal::from_f64(YYY).serialize()`?

**Comment by paupino** [comment]
This is an interesting question. I'll try to break it down:

* `Decimal`s can be compared directly with one another.
* You could possibly consider the `c-repr` feature for `memcmp`. 
* If a `Decimal` has a differing scale and doing a `memcmp` then they would be considered different (e.g. `1.0 != 1.00`) where as `eq` would return `true` (i.e. they are the same number)
* Given identical implementations and numbers of `f32`, they should be able to be comparable.
* Given identical implementations and numbers of `f64`, they should be able to be comparable.
* `f32` parsing and `f64` parsing uses a shared code path and should follow the same rules, however further analysis would need to be done. We could run into the same issue as above with differing scales. That being said, `from_f64` and `from_f32` both try to "round" to capture the intention of the float (e.g. match the scale of the float going in, to the `Decimal` going out).

All in all, I think it _should_ be possible however without some analysis I'd feel a bit unconformable guaranteeing it in _all_ cases.

**Comment by lmatz** [comment]
Thanks a lot for such a detailed answer! 😃 

My current understanding is that having the same scale for all the numbers in comparison is a must. Then I need to `rescale(X)` on all the numbers with the same fixed `X`. Is this always possible? I have runned some tests, and it seems that sometimes after `d.rescale(X)`, `d` would have `d.scale() != X`, and in these non-equal cases, `d.scale()` would be `X-1`. 

Is this by design? Or a limitation can or cannot be bypassed?

**Comment by paupino** [comment]
Are you able to give an example? You may be describing a bug.

**Comment by lmatz** [comment]
<img width="809" alt="Screen Shot 2022-01-15 at 11 17 36 PM" src="https://user-images.githubusercontent.com/5791930/149626985-7cf7727f-029a-467f-8609-563c5b786b14.png">
<img width="308" alt="Screen Shot 2022-01-15 at 11 17 56 PM" src="https://user-images.githubusercontent.com/5791930/149626990-ca471b13-9129-4631-b7b5-b9a64f6cb4d0.png">

**Comment by paupino** [comment]
Hmm. From the surface level that looks like a bug - I'd expect a rescale to 28 to give a scale of 28. Let me investigate to see what's preventing that last scale placement from occurring. Unfortunately, I can't do it right now but will try to look over the weekend.

**Comment by paupino** [comment]
Ok - so long story short: this is not a bug, however the behavior is definitely not well documented. I've put together a PR #465 to try to capture the behavior and explain it a bit better.

Basically, `rescale` will try to increase the scale as much as it possibly can towards the desired scale. In some of these cases, due to the mantissa representation, it can only rescale up to 27. As you can see, these are typically the larger numbers, which makes sense.

For your case, perhaps, you may want to look at [`normalize`](https://docs.rs/rust_decimal/1.20.0/rust_decimal/prelude/struct.Decimal.html#method.normalize)? This would effectively allow you to drop trailing zero's and compare similar scales.

Related, there are two things I'd like to change in a future PR, though probably both slated for v2 of rust-decimal:
* `rescale` is modified in place, where I'd love for it to be able to put inline. Additionally, it may make sense if there was a function which let you know if the desired scale was unable to be achieved.
* I'd love to have an option to define the size of the decimal by using const generics. It could then control precision, storage units etc.

**Comment by lmatz** [comment]
Truly appreciate your efforts! I will follow your advice 👍
