### ISSUE TITLE
Is it possible to provide Decimal::NAN ?

### ISSUE THREAD

**Issue by monadbobo** [paupino/rust-decimal#466]
In some cases, it is necessary to return to the user the value of a calculation error (e.g. div/0), which is not represented in Decimal.

**Comment by paupino** [comment]
Can you give a little bit of context about why you'd want/need this? At the moment we represent "Nan" via the `Option` type. i.e. it's either a `Decimal` or it's "nothing". e.g. For the `div/0` scenario you'd receive `None` when doing a `checked_div`.

**Comment by c410-f3r** [comment]
IIRC, `fixed`, `bigdecimal-rs` and `decimal-rs` don't have a NaN representation

**Comment by paupino** [comment]
One option here: rather than introduce the concept of `NAN`, we do know whether it is `DivByZero` vs `Overflow` etc. It's feasible that we could return the inability to perform a calculation via the `Result`. 

I'm less inclined to represent `NAN` explicitly but would be open to returning additional information in a calculation via a different function.

**Comment by lukesneeringer** [comment]
Doesn't `Option<Decimal>` (or possibly `Result<Decimal>` in the div/0 case) accomplish the same purpose?

**Comment by cardoe** [comment]
So for pyo3 I'm trying to implement rust_decimal support. Python has `NaN`, `-Infinity` and `+Infinity`. While I understand `NaN` as Option maybe the others make sense to have via flags?

**Comment by Tony-Samuels** [comment]
I think `Decimal` is in a good place as a library that only handles actual numbers. This enables things like `Hash` and `Eq` to be implemented, which can't for `f64` because of `Nan` and infinities.

Given this and the lack of traffic on this ticket, I'm going to close this for now. If you think there's more arguments to be made for adding support for this to `Decimal` then please feel free to re-open.
