### ISSUE TITLE
The inverse of a number is lossy

### ISSUE THREAD

**Issue by c410-f3r** [paupino/rust-decimal#488]
Or more specifically `n != (1.0 / (1.0 / n))`.

Just a minor rounding detail. I guess this behavior is expected from the division operation.

```rust
use core::str::FromStr;
use rust_decimal::{Decimal, MathematicalOps};

pub fn main() {
    let n = Decimal::from_str("94.73808970330406409001943853").unwrap();

    dbg!(
        // 94.73808970330406409001943853
        n,
        // 94.73808970330406409001943847
        Decimal::ONE / (Decimal::ONE / n)
    );

    dbg!(
        // 4.5511161337215356777266491599
        n.ln(),
        // 4.5511161337215356777266491592
        (Decimal::ONE / n).ln().abs()
    );
}

```

**Comment by c410-f3r** [comment]
This issue was created to just inform the current behavior and can be re-opened again if desired

**Comment by paupino** [comment]
This is tricky with the current implementation since we're effectively rounding the type to our fixed precision with each operation. I've been thinking a lot about V2 version of this library leveraging const generics for it's underlying storage mechanism. While that would help reduce the spread it still wouldn't solve it since we'd still need to "box" each operation. 
One way to solve it however could be to introduce the concept of a lazily evaluated operation when dealing with rational numbers (i.e. store `1 / n` which doesn't evaluate until necessary).
Anyway, just brainstorming a bit!

**Comment by schungx** [comment]
Or, alternatively, always keep a few extra bits on hand just to absorb the uncertainties in boxing each operation...
