### ISSUE TITLE
[Request]  Support for Serde Option<Decimal> from and to string

### ISSUE THREAD

**Issue by benjaminjellis** [paupino/rust-decimal#523]
Hi, 

The crate has the functionality to serialize and deserialize the `Decimal` type from a string like this

```rust
#[derive(Serialize, Deserialize)]
pub struct Account{
    #[serde(with = "rust_decimal::serde::str")]
    pub cash: Decimal
}
```

but it would also be useful to do this for optional fields, i.e. something like 

```rust
#[derive(Serialize, Deserialize)]
pub struct Account{
    #[serde(with = "rust_decimal::serde::option_str")]
    pub cash: Option<Decimal>
}
```

I had a quick go as implementing this but wasn't able to make much progress.

**Comment by paupino** [comment]
Thanks for the question! The error this gives is a little ambiguous - effectively, it is complaining that during deserialization it doesn't know what to do. This can be fixed by adding `default` to your field attribute:

```
#[derive(Serialize, Deserialize)]
pub struct Account{
    #[serde(default, with = "rust_decimal::serde::str")]
    pub cash: Option<Decimal>
}
```

This tells serde that if the field isn't present then a `None` value will suffice. 

Does this solve your problem, or are you looking for something more complex here? Either way, I could probably document this a bit more since it isn't immediately obvious.
