### ISSUE TITLE
Document how to get the integer portion of a Decimal (as an int).

### ISSUE THREAD

**Issue by lukesneeringer** [paupino/rust-decimal#554]
I think it should be (for a Decimal value `d`) something like:

```rs
let i: i64 = d.round().mantissa().try_into().expect("Too big.");
```

I like this because I get to decide floor / ceil / round behavior. But the contract of `round` (or `floor` or `ceil` for that matter) don't actually guarantee that the decimal returned as a result of the operation will have a `scale` of 0. In fact, I haven't yet looked at the code to see if it even does set the scale to 0 (although I previously determined that `round_dp` set the scale as desired).

The following `round` implementation would be valid as best as I understand it, and not a _du jure_ user-facing change according to the current documentation (even though I bet it is a _de facto_ one):

```rs
pub fn round(&self) -> Self {
  let mut new = self.clone();
  let factor = 10 * self.scale();
  new.mantissa = self.mantissa() / factor * factor;
  new
}
```

I can rescale myself (and for my purposes it'd be fine to ignore the lack of guaranteed success in rescale -- that's a problem in theory but not practice for my needs), but that's sort of annoying because it breaks the chain, since `rescale` modifies in-place.

```rs
let rounded = {
  let mut r = d.round();
  r.rescale(0);
  r
};
let i: i64 = rounded.mantissa().try_into().expect("Too big");

```

**What I want:** I want an int with everything before the decimal point. What's the blessed way to get it?

**Comment by paupino** [comment]
> But the contract of round (or floor or ceil for that matter) don't actually guarantee that the decimal returned as a result of the operation will have a scale of 0. In fact, I haven't yet looked at the code to see if it even does set the scale to 0 (although I previously determined that round_dp set the scale as desired).

Can you provide an example whereby this isn't the case? 

`round` behind the scenes just does a `round_dp(0)` so it'd be odd for it not to work in one and not the other. `round_dp_with_strategy` (which both ultimately call) also explicitly sets the scale to the requested number of decimal places (except for a few unique cases e.g. rounding to a higher number of places). The documentation for `round` also asserts that an integer is returned too so if that's not behaving as expected then it's a bug: https://docs.rs/rust_decimal/latest/rust_decimal/struct.Decimal.html#method.round

Consequently, `ceil` and `floor` use `trunc` behind the scenes which also force an integer value (i.e. scale 0) with the docs asserting as such also.

To note: you could also skip getting the mantissa directly and simply try to convert to an `i64` directly since `TryFrom` is implemented for `Decimal`/`i64` which provides `TryInto` for free:

```rust
use rust_decimal_macros::dec;

fn main() {
    let d = dec!(123.456);
    let i: i64 = d.round().try_into().expect("Too big.");
    assert_eq!(123_i64, i);

    // round() uses bankers rounding by default. Utilize `round_db_with_stragegy` for more configurability
    let d = dec!(234.567);
    let i: i64 = d.round().try_into().expect("Too big.");
    assert_eq!(235_i64, i);
}
```

Regarding `rescale` not utilizing a builder-like pattern - unfortunately this was a design mistake I made early on. There is a ticket tracking this, which also has a workaround if necessary here: #391. 

Btw, there is a good change I'm misunderstanding what you're trying to achieve though - so let me know if I've misinterpreted something!

**Comment by paupino** [comment]
I guess, one last thing. Because `TryFrom` is implemented, you could skip the rounding if you wanted _less_ control. It  effectively does a `trunc` behind the scenes (similar to a force cast into an integer):

```rust
use rust_decimal_macros::dec;

fn main() {
    let d = dec!(123.456);
    let i: i64 = d.try_into().expect("Too big.");
    assert_eq!(123_i64, i);

    let d = dec!(234.567);
    let i: i64 = d.try_into().expect("Too big.");
    assert_eq!(234_i64, i);
}
```

**Comment by lukesneeringer** [comment]
Oh, `try_into()` is probably the way for me to go. Thanks! (I don't need the fine-grained control.)

> Can you provide an example whereby this isn't the case?

No. I was just worried that it wasn't contractual. :-) But direct `try_into` definitely is.
