### ISSUE TITLE
Calculation order affect result

### ISSUE THREAD

**Issue by z-Wind** [paupino/rust-decimal#561]
```rust
let a = Decimal::new(7, 0) / Decimal::new(5, 0);
let b = Decimal::new(10, 0) / Decimal::new(9, 0);
assert_eq!(
    a * b,
    (Decimal::new(7, 0) / Decimal::new(5, 0)) * (Decimal::new(10, 0) / Decimal::new(9, 0))
); // => Pass
assert_eq!(
    a * b,
    Decimal::new(7, 0) / Decimal::new(5, 0) * Decimal::new(10, 0) / Decimal::new(9, 0)
); // => Fail
```
```
left: `1.5555555555555555555555555555`,
right: `1.5555555555555555555555555556`'
```
I guess that the precision of 28 causes that result.
Are there any methods to avoid this?

**Comment by paupino** [comment]
Unfortunately, this is expected behavior in the current implementation of Rust Decimal due to each operation being evaluated, feeding the result into the next one. Effectively, without brackets order of operations applies at the `std::op` level. As expected, Division and Multiplication are equal in terms of order of precedence (i.e. it's why you have BEDMAS vs PEMDAS etc - multiplication and division are interchangeable in these systems).

The current workaround is to use brackets. In this particular example the first assertion is equivalent to the `a` & `b` calculations - since `a` & `b` are statements these can be thought of as have brackets surrounding them. The second assertion however is _technically_ not equivalent due to order of execution.

All that said, brackets won't solve everything. For example: 

```rust
println!("{}", dec!(1) / dec!(3) * dec!(3));
println!("{}", (dec!(1) / dec!(3)) * dec!(3));
```

Due to operator evaluation we will get `0.9999999999999999999999999999` for both of these. The current fix for this would be to rearrange the operators which is often easier said than done:

```rust
println!("{}", dec!(1) * dec!(3) / dec!(3)); // Outputs 1
```

The longer answer which has been discussed though yet to be implemented, is to delay evaluation until absolutely required instead of performing an evaluation each operation (e.g. https://github.com/paupino/rust-decimal/issues/511#issuecomment-1112836946). This would be useful in many different scenarios - in particular when performing mathematical functions. My initial thinking is that this would use an intermediary format to be used to maintain maximum precision (i.e. perhaps a ratio)- all in all, it's an experiment I want to take a look into when we start work on v2 of the library.

Anyway, does this help at all? If I've parsed your question incorrectly, please let me know!

**Comment by schungx** [comment]
@z-Wind   That's the definition of 28-digit precision.  It means that the 29th digit does not need to be correct.  Technically speaking, it can even come up with a different number for the same calculation; it won't be deterministic, but it will be correct to the set precision.

Therefore, round the number to the max precision before you do any comparisons.

**Comment by z-Wind** [comment]
Thanks a lot. 
This is really a great library.
I will looking forward to the implementation of v2 of the library.
