### ISSUE TITLE
To f64 losing accuracy for `100000.000000000000000000`

### ISSUE THREAD

**Issue by zzhengzhuo** [paupino/rust-decimal#624]
When `100000.000000000000000000` converting to f64, it will lose accuracy.
But for `10000.000000000000000000` and `1000000.000000000000000000`, it works well.

The test code is 
```
#[test]
fn test_decimal() {
    let decimal = Decimal::from_str_exact("100000.000000000000000000").unwrap();
    dbg!(f64::try_from(decimal).unwrap());
    let decimal = Decimal::from_str_exact("1000000.000000000000000000").unwrap();
    dbg!(f64::try_from(decimal).unwrap());
    let decimal = Decimal::from_str_exact("10000.000000000000000000").unwrap();
    dbg!(f64::try_from(decimal).unwrap());
}
```

The result is

<img width="708" alt="image" src="https://github.com/paupino/rust-decimal/assets/48124374/a7facf9a-0d33-4ee2-af73-f0f31124cf56">

The rust-decimal version is `1.32.0`

**Comment by paupino** [comment]
This appears to be related to the rounding that is happening during `to_f64`:

```rust
let round_to = 10f64.powi(self.scale() as i32);
Some((value * round_to).round() / round_to)
```

In this case, we try doing the following:
```
100000000000000000000000 / 1000000000000000000
```
This fails in the last case due to an approximation issue. Interestingly enough this doesn't need to be rounded since we're already dealing with an integer due to a zero fractal component so we can just return early. I'll whip together a PR demonstrating this.
