### ISSUE TITLE
too rubbish to called rust decimal

### ISSUE THREAD

**Issue by zzy444626905** [paupino/rust-decimal#629]
···
    let result = Decimal::from_str("111111111111111111111111111111111111111111111111111111111111111111").unwrap();
    println!("{}", result);
···

···
ErrorString("Invalid decimal: overflow from too many digits")
···

**Comment by schungx** [comment]
Not necessary to be rude.  You don't have to use it if it doesn't suit you.

**Comment by Tony-Samuels** [comment]
You might be interested in BigDecimal if you want arbitrarily sized decimal numbers. This crate is for constant size, no allocation decimals.

**Comment by paupino** [comment]
Thanks folks! I've used this as an opportunity to update the readme to add a section calling out when this library may not be suitable and to highlight alternatives. Feel free to take a look and as always if something looks off or could be explained better then let me know (or open a PR). 

In the meantime, I'll close this issue since there isn't anything actionable (other than readme clarification) that can be done.
